### ISSUE TITLE
getPoolBaseApr too low? (hour vs. day)

### ISSUE THREAD

**Issue by uwe** [convex-community/convex-subgraph#17]
I'm studying the `curve-pools` subgraph. In `src/services/apr.ts` in `getPoolBaseApr` the variable names talk about the "previous day", but from the timestamp is only subtracted an hour. So, should the `baseApr` be 24 times higher?

**Comment by benber86** [comment]
Hey, thanks for spotting this! We actually just switched from daily snapshots to hourly snapshots for the pools so that the front-end would be more responsive, and I missed this.
Will rename the variables and add the 24 hours multiplication.
