### ISSUE TITLE
crv-emissions subgraph failed

### ISSUE THREAD

**Issue by olgadk7** [convex-community/convex-subgraph#41]
Hello, ty for all the subgraphs you put out there. 

What happens when a subgraph fails? [crv-emissions](https://thegraph.com/hosted-service/subgraph/convex-community/crv-emissions) one currently gives "message": "indexing_error"..

**Comment by olgadk7** [comment]
It came back on. Curious, how often do those indexing errors happen? Is there a way to prevent them? TY.

**Comment by benber86** [comment]
They do not happen often, it seems that in this particular case the issue came from the graph's hosted service.
